#!/usr/bin/env bash

if [ ! -f "/etc/moltony-wallpaper-changer.conf" ]; then
    echo "No config file found please consult the configs docs" 1>&2
    exit 1
fi

source /etc/moltony-wallpaper-changer.conf

echo "changing wallpaper"
DISPLAY=$Mwc_Display XAUTHORITY=$Mwc_Xauthority /usr/bin/feh --bg-fill --randomize "$Mwc_Wpfolder/"
