#!/usr/bin/bash

if [ ! -f "/etc/thprac-launch-script.conf" ]; then
	echo "CONFIG NOT FOUND"
	exit 1
fi

source /etc/thprac-launch-script.conf

if [ "$ThpracPattern" == "" ]; then
	echo "thprac pattern not set"
	exit 2
fi

if [ "$ThpracPrefix" == "" ]; then
	echo "thprac prefix not set"
	exit 3
fi

prac_wild=( "$ThpracPattern" )
prac_exe="${prac_wild[0]}"
WINEPREFIX="$ThpracPrefix" wine $prac_exe
