#!/usr/bin/env bash

alias gpllsh='git pull && git push' # Pull'n'push
alias gplsh='gpllsh' # Pul'n'push
alias plsh='gpllsh' # Pl'n'sh
alias cdgr='cd `git rev-parse --show-toplevel`' # Go to root of git repository
alias glog='git log' # Git log shortcut
alias gloga='git log --all' # git log shortcut for all branches
alias glga='gloga' # gloga w/o o
alias todayscommits='glog --oneline --since=midnight' # Show all commits starting from midnight
alias numcommits='glog --oneline | wc -l' # Count total number of commits in the repo
alias numcommtoday='todayscommits | wc -l' # Count total number of commits that were created today in a repo
alias yesterdayscommits='glog --oneline --since=yesterday.midnight --until=midnight' # List all commits from yesterday
alias numcommyest='yesterdayscommits | wc -l' # Count total number of commits that were created yesterday in a repo
alias gcam='git commit -am' # do commit
alias gpsh='git push' # Push local changes to remote in git
alias gpsht='git push --tags' # Push local tags to remote in git
alias gpll='git pull' # Pull remote changes to local repo in git
alias gftch='git fetch' # Fetch (git)
alias gcln='git clone' # Clone a repo (git)
alias gcfgg='git config --global' # Change/view global git configuration
alias gcfgun='gcfgg user.name' # Set user's name in git
alias gcfgue='gcfgg user.email' # Ser user's email git
alias gshw='git show' # Show differences between commit and a commit before that
alias glogol='glog --oneline' # git log with each commit taking 1 line
alias glgol='glogol' # Short glogol
alias gr.='git restore .' # Remove local unstaged changes in current dir
alias grs='git restore' # Remove local unstaged changes (git)
alias ga.='git add .' # Stage local changes in cur. directory (git)
alias gdd='git add' # Stage local changes (git)
alias gcm='git commit -m' # Do a commit (git)
alias gcobj='git count-objects' # Count how many objects and how much the repo takes up (git)
alias glgolrv='glogol --reverse' # Git log one line but in reverse
alias gbch='git --no-pager branch' # Git branch
alias gbchvv='git --no-pager branch -vv' # Git branch with more info
alias gslog='git shortlog' # Git short log
alias pshpaipai='git push && paipai' # Git push and papiap
alias gshwnp='git --no-pager show' # Git show with no pager
alias gdffnp='git --no-pager diff' # git diff ith no pager
alias gundolc='git reset --soft HEAD^' # This is when i screw up
alias gundolchard='git reset --hard HEAD^' # This is when i really screw up
alias glgnp='git --no-pager log' # Git log with no pager
alias glgnpr='glgnp --reverse' # Git log no pager reverse
alias glgrnp='glgnpr' # Different spelling of the above alias
alias glognp='glgnp' # Git log no pager
alias glognpr='glgnpr' # Git log no pager reverse
alias glogrnp='glgnpr' # Git log reverse no pager
alias glogolnp='git --no-pager log --oneline' # Git log no pager oneline
alias glogolrnp='glogolnp --reverse' # Git log one one line no pager reverse
alias glogolnpr='glogolrnp' # Git log one line no pager reverse
alias glgolnp='glogolnp' # Git log one line no pager
alias glgolrnp='glogolrnp' # Git log one line reverse no pager
alias glogolnpr='glogolrnp' # Git log one line no pager reverse
alias gint='git init' # initialzie git repository
alias :G='git' # Git
alias gpshpaipai='gpsh && paipai' # Git push pai pai
alias gagcm='git add . && git commit -m' # Git add and commit
alias gshh='git show HEAD' # Show head
alias gshwh='gshh' # In case i forgor
alias gshhnp='git --no-pager show HEAD' # Show head without pager
alias gcaaem='git commit -a --allow-empty-message' # Commit with empty message
alias glf='git ls-files' # List git files
alias i-forgor-submodules='git submodule update --init --recursive' # I FORGOR SUBMODULES!!!
alias glogrv='git log --reverse' # I cannot believe I'm only now adding this
alias glgrv='glogrv' # Like, could you believe it? I've had these aliases for over half a year, and still have not thought of a simple reverse-log alias?..
alias glgr='glgrv' # :(){ :|:& };:
alias gsw='git switch' # switch to some branch idk
alias gswc='git switch -c' # Switch to some brach but like make it
alias gadbch="git fetch -p && LC_ALL=C git branch -vv | grep ': gone]' | awk '{print \$1}' | xargs -r git branch -d" # Git auto delete branches
alias gpshf='git push --force' # Pushpushpush
alias grgpll='gr. && gpll' # Remove all local changes and pull
alias gsw-='git switch -' # Switch to default branch
alias gplladbch='git pull && gadbch' # Pull and then auto-delete branches
alias gsw-plladbch='git switch - && gplladbch' # Switch to main branch, then pull, then auto-delete branches
alias gbchd='git branch -d' # Delete a branch
alias gbchdf='git branch -D' # Force delete a branch
alias gbchm='git branch -m' # Move/rename a branch
alias gbchmf='git branch -M' # Force move/rename a branch
alias gbchc='git branch -c' # Copy a branch
alias gbchcf='git branch -C' # Force copy a branch
alias gbcha='git branch -a' # List every branch ever
alias glgolth='glgth --oneline' # git log tag..HEAD one line
alias gchk='git checkout' # git checkout
alias gpog='git push origin' # git push to origin
alias gpgh='git push github' # git push to github
alias gpogmn='git push origin main' # git push main to origin
alias gpogms='git push origin master' # git push master to origin
alias gpghmn='git push github main' # git push main to github
alias gpghms='git push github master' # git push master to github
alias gfch='git log --follow -p --' # view commit history and diffs for file
alias gplogmn='git pull origin main' # git pull main to origin
alias gplogms='git pull origin master' # git pull master to origin
alias gplghmn='git pull github main' # git pull main to github
alias gplghms='git pull github master' # git pull master to github
alias gmg='git merge' # git merge
alias gpshu='git push -u' # git push upstream
alias gpshuo='gpshu origin' # git push -u origin
alias gtg='git tag' # git tag
alias gtg-howto='echo -e "annotated -> git tag -a tag-name -m message\nnot annotated -> git tag tag-name\ndefault is HEAD, append commit hash to specify"' # cheet sheet
alias gppt='gpsh && gpsht' # push and tags
alias gpshtf='gpsht --force' # force push tags
alias gpptf='gppt --force' # psuh and tags force
